# generated by datamodel-codegen:
#   filename:  MRI_schema.json
#   timestamp: 2026-09-04T14:32:07+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any, List, Optional, Union

from pydantic import BaseModel, Field


class Affiliation(BaseModel):
    institutionName: Optional[str] = None
    institutionAcronym: Optional[str] = None
    institutionDepartment: Optional[str] = None
    institutionID: Optional[str] = None


class User(BaseModel):
    name: Optional[str] = None
    role: Annotated[
        Optional[str],
        Field(
            description="Role of the user to be selected from: *data curator, *instrument scientist, *team leader, *team member"
        ),
    ] = None
    affiliation: Optional[Affiliation] = None
    email: Optional[str] = None


class Unit(Enum):
    nm = "nm"
    um = "um"
    mm = "mm"
    cm = "cm"
    m = "m"


class SampleSize(BaseModel):
    value: Optional[float] = None
    unit: Optional[Unit] = "m"


class Unit1(Enum):
    kg = "kg"
    g = "g"


class SampleWeight(BaseModel):
    value: Optional[float] = None
    unit: Optional[Unit1] = "kg"


class Unit2(Enum):
    T = "T"


class MeasurementConditions(BaseModel):
    value: Optional[float] = None
    unit: Optional[Unit2] = "T"


class Sample(BaseModel):
    sampleName: Optional[str] = None
    sampleID: Optional[str] = None
    sampleSize: Annotated[Optional[SampleSize], Field(description="Length or size of the sample, in meters.")] = None
    sampleWeight: Annotated[Optional[SampleWeight], Field(description="Weight of the sample, in kilograms.")] = None
    measurementConditions: Annotated[
        Optional[MeasurementConditions], Field(description="Nominal field strength of the MR Magnet, in Tesla.")
    ] = None


class InstrumentManufacturer(BaseModel):
    manufacturerName: Optional[str] = None
    modelName: Optional[str] = None
    manufacturerID: Optional[str] = None


class Instrument(BaseModel):
    instrumentName: Optional[str] = None
    instrumentID: Optional[str] = None
    instrumentManufacturer: Optional[InstrumentManufacturer] = None


class Unit3(Enum):
    ms = "ms"


class EffectiveEchoTime(BaseModel):
    value: Optional[Union[float, List[Any]]] = None
    unit: Optional[Unit3] = "ms"


class RepetitionTime(BaseModel):
    value: Optional[Union[float, List[Any]]] = None
    unit: Optional[Unit3] = "ms"


class Unit5(Enum):
    degree = "degree"
    field_ = "°"


class FlipAngle(BaseModel):
    value: Optional[Union[float, List[Any]]] = None
    unit: Optional[Unit5] = "degree"


class SequenceProtocol(BaseModel):
    sequenceProtocolName: Optional[str] = None
    effectiveEchoTime: Annotated[
        Optional[EffectiveEchoTime],
        Field(
            description="Time in ms between the middle of the excitation pulse and the peak of the echo signal produced"
        ),
    ] = None
    repetitionTime: Annotated[
        Optional[RepetitionTime],
        Field(
            description="Time in ms between the beginning of a pulse sequence and the beginning of the subsequent (essentially identical) pulse sequence"
        ),
    ] = None
    flipAngle: Annotated[
        Optional[FlipAngle],
        Field(
            description="The amount of rotation in degree the net magnetization experiences during application of a pulse"
        ),
    ] = None


class Unit6(Enum):
    mm = "mm"


class PixelSpacing(BaseModel):
    value: Optional[List[float]] = None
    unit: Optional[Unit6] = "mm"


class SliceThickness(BaseModel):
    value: Optional[float] = None
    unit: Optional[Unit6] = "mm"


class ImageSize(BaseModel):
    rows: Optional[int] = None
    columns: Optional[int] = None


class Unit8(Enum):
    Hz = "Hz"


class PixelBandwidth(BaseModel):
    value: Optional[float] = None
    unit: Optional[Unit8] = "Hz"


class PixelRange(BaseModel):
    pixelBandwidth: Optional[PixelBandwidth] = None
    smallestImagePixelValue: Optional[int] = None
    largestImagePixelValue: Optional[int] = None
    pixelRepresentation: Optional[int] = None


class AllImages(BaseModel):
    numberOfImages: Optional[str] = None
    imageOrientation: Optional[List[Union[float, List[Any]]]] = None
    pixelSpacing: Optional[PixelSpacing] = None
    sliceThickness: Optional[SliceThickness] = None
    imageSize: Optional[ImageSize] = None
    pixelRange: Optional[PixelRange] = None


class PerImageItem(BaseModel):
    imageNumber: Optional[int] = None
    sampleImagePosition: Optional[List[Union[float, List[Any]]]] = None


class Images(BaseModel):
    allImages: Optional[AllImages] = None
    perImage: Optional[List[PerImageItem]] = None


class Series(BaseModel):
    seriesID: Optional[str] = None
    seriesTitle: Optional[str] = None
    sequenceProtocol: Annotated[
        Optional[SequenceProtocol],
        Field(
            description="The parameters of the Instrument which define the conditions under which one or more Measurements are performed and a Series is generated. Usually, there is a set of Protocols that are applied on a routine basis. The choice of a Protocol mainly depends on the Sample, the Instrument and the research question addressed by an Experiment"
        ),
    ] = None
    images: Annotated[
        Optional[Images],
        Field(
            description="The Fourier transformation of spatially encoded signals collected in k-space (Raw Data) as an array of pixel values representing the intensity of mainly the H-atom signals from the Sample."
        ),
    ] = None


class Study(BaseModel):
    studyID: Annotated[Optional[str], Field(description="ID of the Study")] = None
    studyTitle: Annotated[Optional[str], Field(description="Title of the Study")] = None
    studyDateTime: Optional[datetime] = None
    program: Annotated[
        Optional[str], Field(description="Details concerning the program (or software) used for aquisition")
    ] = None
    user: Annotated[
        Optional[User], Field(description="Contact information of the user responsible for the measurement")
    ] = None
    sample: Annotated[
        Optional[Sample],
        Field(
            description="A physical object (or a collection of objects) which is considered as a single discrete, uniquely identified unit which is exposed to the Instrument during one or more Measurements. MRI Samples are usually managed or being placed in a container. The term is equivalent to Specimen"
        ),
    ] = None
    instrument: Annotated[
        Optional[Instrument],
        Field(
            description="Identifiable piece of equipment used by one or more Users to perform one or more Measurements and to generate Raw Data. The Instrument is located in a laboratory hosted by an institution"
        ),
    ] = None
    series: Annotated[
        Optional[List[Series]],
        Field(
            description="A set of one or more Images or Spectra (i.e. Processed Data) generated after the processing of Raw Data collected during Measurements along the z-axis of a Sample as part of the same Study and stored in one or multiple DICOM Files"
        ),
    ] = None


class MagneticResonanceImagingMriSchema(BaseModel):
    study: Annotated[
        Optional[Study],
        Field(
            description="A collection of one or more Series that are scientifically related (depending on the research context) for the purpose of the Experiment"
        ),
    ] = None
