site_name: NEPMetadataMapping
site_description: "Components of a mapping tool that facilitates metadata mapping from file formats used in the NFFA-Europe Pilot (NEP) project to JSON schemas."

repo_url: https://github.com/nicolasblumenroehr/NEP-Metadata-Mapping-Tool
repo_name: nicolasblumenroehr/NEP-Metadata-Mapping-Tool

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "blue"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "blue"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - "Start": index.md
  - "API": api.md
